### PR TITLE
Remove unused imports and variables

### PR DESCRIPTION
**Pull request by kingthorin**
AttackSurfaceDetectorPanel.java - remove unused imports and variables.

### CODE REVIEW

**Comment by matthewD-AVI** [comment]
Can you remove the line adding the icon. I have someone creating an icon specifically for the ASD Zap plugin but I will merge this pr since it has other uses. Thank you for working on this.

**Comment by kingthorin** [comment]
@matthewD-AVI there's no rush on the other stuff. I'm glad for this to wait and I can rebase/fix when the icon is available. Or I can remove the icon stuff from this one (both the new icon and the line), and just provide the unused imports/var changes, then tackle the icon later :)

**Comment by kingthorin** [comment]
OK I'll do the latter, PR update coming.

**Comment by kingthorin** [comment]
For the record (whoever ends up doing it....) when you want to add/set the icon you'll just need to add the png file (ex: `/org/zaproxy/zap/extension/attacksurfacedetector/resources/asd-icon-16.png`) and do something like:
```diff
--- a/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/AttackSurfaceDetectorPanel.java
+++ b/zaproxy/src/org/zaproxy/zap/extension/attacksurfacedetector/AttackSurfaceDetectorPanel.java
@@ -95,7 +95,6 @@
     {
         this.setLayout(new BorderLayout());
         this.setSize(600, 200);
+        this.setIcon(new ImageIcon(AttackSurfaceDetectorPanel.class.getResource("/org/zaproxy/zap/extension/attacksurfacedetector/resources/asd-icon-16.png")));
 
         JPanel basePanel = new JPanel();
         basePanel.setLayout(new java.awt.GridBagLayout());
```

If you get something that looks decent at 10px we could also set the site tree icon with a custom source icon (like the spiders, fuzzer, brute force, etc do).

**Pull request merged**
